라이더 로그인 기능 구현
boostcamp-2020/Project09-C-Uber-Clone pull request #20
Opened 2020-11-24 12:26 UTC by ahrimy

## 개요
- 서버에서의 라이더 로그인 기능 로직 구현

## 작업사항
- `graphql-passport`설정
- `loginRider` mutation 의 typeDef, resolver 추가

## 기타
- 클라이언트와 연동 추가 작업 필요

2020-11-24 14:42 UTC, kkole3897 requested changes
수고하셨습니다. 👍 
중간 중간에 console.log() 있는 부분이랑 import할 때 index 붙여준 부분 스타일만 바꾸면 좋을 것 같습니다.

2020-11-24 14:42 UTC, kkole3897 commented on server/src/graphql/types/rider.graphql
> +}
혹시 rider.graphql 파일 안에 나중에 Rider type 정의 하고 Query type도 같이 정의하는게 맞나요?

2020-11-24 14:42 UTC, kkole3897 commented on server/src/repositories/driver.ts
>  };
저번에 할 때 lint error 떠서 분리했던 건데 안 뜨면 이렇게 하는게 저도 더 좋다고 생각합니다.

2020-11-24 14:42 UTC, kkole3897 commented on client/src/slice.ts
> +  console.log(data); //로그인한 유저의 id
```suggestion
```
console.log() 단순 확인 용도로 있는건가요?

2020-11-24 14:42 UTC, kkole3897 commented on server/src/passport/local.ts
> +import { Rider } from '../repositories/index';
index는 따로 안 붙여줘도 자동으로 찾아줘요.

2020-11-24 14:42 UTC, kkole3897 commented on server/src/app.ts
> +    console.log('login');
```suggestion
  if (authenticationResolver.includes(req.body.operationName)) {
```
console.log()가 단순 확인 용도라면 없어도 될 것 같습니다.

2020-11-24 15:06 UTC, ahrimy commented on server/src/graphql/types/rider.graphql
> +}
넵 rider 관련된 type들은 이 파일에 추가하면 될 것 같습니다!

2020-11-24 15:07 UTC, ahrimy commented on client/src/slice.ts
> +  console.log(data); //로그인한 유저의 id
이 부분은 로그인 후에 아무런 로직이 없어서 우선 임시로 넣어놨습니다ㅜㅜ

2020-11-24 15:08 UTC, ahrimy commented on server/src/passport/local.ts
> +import { Rider } from '../repositories/index';
오 그러게요 index 왜 썼을까요....수정할게요!

2020-11-24 15:08 UTC, ahrimy commented on server/src/app.ts
> +    console.log('login');
넵 이것도 놓칠뻔 했네용 수정해놓을게요 감사합니다!

2020-11-24 15:38 UTC, kkirico approved these changes
서비스에있는 라이더가 이해가 안가네요...
내일 설명 부탁드려요ㅋㅋ
꼼꼼하게 코드 정리하시고 구현하시느라 수고 많으셨습니다! 😃

2020-11-24 15:38 UTC, kkirico commented on client/src/queries/login.ts
> +}`;
미천한 제 눈엔 변화가 안느껴집니다ㅠㅠ
전후가 어떻게 다른 쿼리였는지 설명 해주실 수 있을까요?
맨 마지막 { String } 만 빠진건가요?

2020-11-24 15:38 UTC, kkirico commented on server/src/repositories/rider.ts
>  };
꼼꼼하게 손봐주셔서 감사합니다!

2020-11-25 00:54 UTC, ahrimy commented on client/src/queries/login.ts
> +}`;
이부분이 원래 `email`,`password` 데이터를 받아서 쿼리를 만들었었는데, 
찾아보니까 쿼리에는 어떤 데이터가 들어가는지 명시만 해주면 되고,
`slice.ts`의 `requestLogin`함수에서의 `client.mutate` 의 옵션 중에 하나인 `variables`에 실제 `email`과 `password` 데이터를 넣어줬습니다!
이따가 다시 한번 말씀드릴게용!

2020-11-25 01:00 UTC, passwd10 reviewed
고생하셨습니다 아림님! review 확인부탁드려요~ :smile:

2020-11-25 01:00 UTC, passwd10 commented on client/src/slice.ts
> +    variables: { ...loginField },
인자를 함수로 받을필요 없이 variables 가 알아서 넣어주는건가요??

2020-11-25 01:00 UTC, passwd10 commented on server/src/app.ts
> +  }
body에 operationName은 없는데 header에 authorization이 있으면 어떻게되는건가요?

2020-11-25 01:00 UTC, passwd10 commented on server/src/services/rider.ts
> +      return user._id;
user._id는 DB에서만 사용되는 id라 return해줄 필요가 없다는 의견인데 어떻게 생각하시나요? :thinking:

2020-11-25 01:13 UTC, ahrimy commented on client/src/slice.ts
> +    variables: { ...loginField },
넵 맞습니다!

2020-11-25 01:14 UTC, ahrimy commented on server/src/services/rider.ts
> +      return user._id;
이부분은 로그인 후에 토큰 발급해주는 로직이 추가되어야하는데 아직 완성이 안돼서
임시로 id 를 반환하도록 해뒀습니다!

2020-11-25 01:16 UTC, ahrimy commented on server/src/app.ts
> +  }
있으면 유효한 토큰인지 확인하는 과정을 거쳐서 resolver로 넘어가는데
로그인 토큰 발급 로직 추가 후에 진행될 부분입니다!

2020-11-25 01:17 UTC, kkirico commented on client/src/queries/login.ts
> +}`;
아 무슨말인지 알겠어요!ㅋㅋㅋ
설명 감사합니다링

2020-11-25 01:27 UTC, passwd10 approved these changes

2020-11-25 01:47 UTC, kkole3897 approved these changes
수고하셨습니다. 👍

2020-11-25 01:47 UTC, merged