subscription 인증 구현
boostcamp-2020/Project09-C-Uber-Clone pull request #41
Opened 2020-11-30 09:47 UTC by ahrimy

## 개요
- subscription 요청 시 token을 통한 인증

## 작업사항
- `jwt.verify()`를 사용하여 토큰 확인
- 해당 유저 조회
- 웹소켓 요청과 http 요청에 따라서 context 구분
- jwt 토큰 발급 및 확인 모듈 분리

## 기타

2020-11-30 14:30 UTC, passwd10 approved these changes
subscription 인증 결국 해내셨군요 :100: 

한가지 궁금하게 있습니다! passport-jwt를 이용하면 jwt를 발급해주는걸로 아는데 jwt라이브러리로 jwt를 발급해주신 이유가 있을까요?

2020-11-30 14:30 UTC, passwd10 commented on server/src/utils/signToken.ts
> +};
중복되는 함수를 util로 분리하셨군요! 좋습니다 :+1:

2020-11-30 14:30 UTC, passwd10 commented on server/src/app.ts
> +  },
context에 connection을 주입하는 부분을 못 찾겠는데, connection상태가 어떻게 들어가는건가요~?

2020-11-30 14:36 UTC, kkole3897 requested changes
수고하셨습니다. 👍 
아직 저는 subscription 이해가 완벽하지 않아 100% 이해하지 못했지만...

2020-11-30 14:36 UTC, kkole3897 commented on server/src/app.ts
> +
개행이 추가로 들어갔네요.

2020-11-30 14:36 UTC, kkole3897 commented on server/src/utils/verifyToken.ts
> +    const email = (decoded as TokenInterface).email;
```suggestion
    const { isDriver, email } = decoded as TokenInterface;
```
이렇게는 못 쓰나요?

2020-11-30 14:36 UTC, kkole3897 commented on server/src/app.ts
> +    onConnect: async (connectionParams:{Authorization?:string}, webSocket, context) => {
`connectionParams`가 client에서 subscription 연결을 하면서 전달하는 parameter 맞나요?

2020-11-30 14:50 UTC, kkirico approved these changes
구조가 이해하기 쉽고 좋네요!

2020-11-30 15:05 UTC, ahrimy commented on server/src/app.ts
> +  },
subscription 을 생성하는 요청(?) 은 `connection`을 포함하고 있고, 
query나 mutation은 `req`, `res` 를 포함하고 있다고 합니다!

그래서 위에 코드처럼 connection 이 존재하는 경우에는 subscription 관련된 요청이라고 생각해서 
`connection.context`를 context의 값으로 설정하고
그 이외는 query, mutation이라고 생각해서 `buildContext({req,res})`의 반환값을 context로 설정해줬습니당
[Context with Subscriptions
](https://www.apollographql.com/docs/apollo-server/data/subscriptions/#context-with-subscriptions) 
이거 한번 보시면 좋을거 같습니당

2020-11-30 15:11 UTC, ahrimy commented on server/src/app.ts
> +
수정했습니다!

2020-11-30 15:12 UTC, ahrimy commented on server/src/utils/verifyToken.ts
> +    const email = (decoded as TokenInterface).email;
이걸 몰라서 한참 헤맸는데 이렇게 할 수 있었네요.....수정했습니다!

2020-11-30 15:13 UTC, ahrimy commented on server/src/app.ts
> +    onConnect: async (connectionParams:{Authorization?:string}, webSocket, context) => {
넵 맞습니당!

2020-11-30 15:57 UTC, passwd10 commented on server/src/app.ts
> +  },
오...그렇군요 감사합니다! :+1:

2020-12-01 01:08 UTC, kkole3897 approved these changes

2020-12-01 01:15 UTC, merged